#!/usr/bin/env node
'use strict';
const os = require('os');
const path = require('path');

const download = require('./index');

if (process.env.MYSTERIUM_CLIENT_PREVENT_LOCAL_INSTALL === 'true') {
  console.log('Mysterium_client binary installation is prevented. Please use download-mysterium-client now.');
  process.exit();
}

const [,, ...args] = process.argv;
const osType = args[0] || os.type();
const osArch = 'x64';

const destination =  args[1] ? path.resolve(args[1]) : path.resolve(__dirname, 'bin');

download(osType, osArch, destination);
